<footer class="col-12" >
  <!-- Logos -->
  <div class="container">

    <div class="row text-center" id="sponsors">

      <div class="col-12  text-center">
                <img class="img-fluid d-none d-lg-block" src="images/sponsors.png" />
                <img class="img-fluid d-none d-sm-block d-lg-none" src="images/sponsor_medio.png" />
                <img class="img-fluid d-block d-sm-none" src="images/sponsor_medio.png" />
      </div>

    </div>

  </div>

  <!-- Texto -->
  <div class="row">

    <div class="col-12 text-center">

      <p>© 2019 Montevideo Music Box</p>

    </div>

  </div>
</footer>
