
<!-- Sidebar -->
<ul class="sidebar navbar-nav">

  <!-- Inicio -->
  <li class="nav-item active">
    <a class="nav-link" href="index.php">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Panel de control</span>
    </a>
  </li>

  <!-- Eventos -->
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      <i class="fas fa-fw fa-calendar"></i>
      <span>Eventos</span>
    </a>
    <div class="dropdown-menu" aria-labelledby="pagesDropdown">
      <a class="dropdown-item" href="FormEventosINS.php"><i class="fas fa-fw fa-plus"></i>&nbsp Nuevo evento</a>
      <a class="dropdown-item" href="verEventos.php"><i class="fas fa-fw fa-wrench"></i>&nbsp Administrar</a>
      <a class="dropdown-item" href="verHistorico.php"><i class="far fa-calendar-plus"></i>&nbsp Histórico</a>

    </div>
  </li>

  <!-- Categorias -->
  <li class="nav-item">
    <a class="nav-link" href="FormCategoriasINS.php">
      <i class="fas fa-fw fa-clipboard-list"></i>
      <span>Categorías</span></a>
  </li>

  <!-- Usuarios -->
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      <i class="fas fa-fw fa-user"></i>
      <span>Usuarios</span>
    </a>
    <div class="dropdown-menu" aria-labelledby="pagesDropdown2">
      <a class="dropdown-item" href="FormUsuarioREG.php"><i class="fas fa-fw fa-plus"></i>Nuevo usuario</a>
        <a class="dropdown-item" href="MisDatos.php"><i class="fas fa-fw fa-wrench"></i>Mi perfil</a>

    </div>
  </li>

  <!-- Salir -->
  <li class="nav-item">
    <a class="nav-link" href="Salir.php">
      <i class="fas fa-fw fa-times"></i>
      <span>Salir</span></a>
  </li>

</ul>
