<nav class="navbar sticky-top navbar-expand navbar-dark tatic-top" id="nav-usr">

  <a class="navbar-brand mr-1" href="index.php">Montevideo Music Box</a>

  <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
    <i class="fas fa-bars"></i>
  </button>

  <a href="../index.php" class="ml-auto text-light text-transform-none d-none d-md-inline" target="_blank">Ir a la página</a>

</nav>
